### ISSUE TITLE
A dependency must not be empty

### ISSUE THREAD

**Issue by mcxinyu** [mainlxl/Android-So-Handler#3]
你好，按照 readme 中的流程接入，得到下面的错误

```
org.gradle.api.ProjectConfigurationException: A problem occurred configuring project ':app'
	at org.jetbrains.plugins.gradle.model.ProjectImportAction.execute(ProjectImportAction.java:125)
	at org.jetbrains.plugins.gradle.model.ProjectImportAction.execute(ProjectImportAction.java:42)
Caused by: org.gradle.api.InvalidUserDataException: A dependency must not be empty
	at com.imf.plugin.so.ApkSoFileAdjustPlugin.createTask(Plugin.kt:169)
	at com.imf.plugin.so.ApkSoFileAdjustPlugin.afterProjectEvaluate$lambda-1(Plugin.kt:139)
	at com.imf.plugin.so.ApkSoFileAdjustPlugin.afterProjectEvaluate(Plugin.kt:137)
	at com.imf.plugin.so.SoFilePlugin.apply$lambda-0(Plugin.kt:35)
	at jdk.proxy1/jdk.proxy1.$Proxy50.afterEvaluate(Unknown Source)
	at org.jetbrains.plugins.gradle.model.ProjectImportAction.execute(ProjectImportAction.java:125)
	at org.jetbrains.plugins.gradle.model.ProjectImportAction.execute(ProjectImportAction.java:42)
```

大概就是这行代码异常了
https://github.com/Android-Mainli/Android-So-Handler/blob/61c934a81010164c4003edda834cc38de45d2253/file-plugin/src/main/kotlin/com/imf/plugin/so/Plugin.kt#L169

请帮忙看看，需要怎么调试呢？

**Comment by mcxinyu** [comment]
调试了一下，发现我的项目里面 package 相关的 task 只有这几个
![image](https://user-images.githubusercontent.com/9566116/222310273-226f9773-b65d-4802-9da1-8a0ab791f7c3.png)

```
packageBetaArm64Debug
packageBetaArm64DebugAndroidTest
packageBetaArm64DebugBundle
packageBetaArm64DebugUniversalApk
packageBetaArm64Release
packageBetaArm64ReleaseBundle
packageBetaArm64ReleaseUniversalApk
packageNjfArm64Release
packageNjfArm64ReleaseBundle
packageNjfArm64ReleaseUniversalApk
packageNjfRelease
packageNjfReleaseBundle
packageNjfReleaseUniversalApk
```

也就是说下面两处逻辑会报错
https://github.com/Android-Mainli/Android-So-Handler/blob/61c934a81010164c4003edda834cc38de45d2253/file-plugin/src/main/kotlin/com/imf/plugin/so/Plugin.kt#L137

https://github.com/Android-Mainli/Android-So-Handler/blob/61c934a81010164c4003edda834cc38de45d2253/file-plugin/src/main/kotlin/com/imf/plugin/so/Plugin.kt#L142

**Comment by zwwxj** [comment]
我也遇到同样的问题，请问楼主怎么解决呢？

**Comment by mcxinyu** [comment]
> 我也遇到同样的问题，请问楼主怎么解决呢？

可以参考我的分支 [mcxinyu/Android-So-Handler](https://github.com/mcxinyu/Android-So-Handler)

**Comment by zwwxj** [comment]
> > 我也遇到同样的问题，请问楼主怎么解决呢？
> 
> 可以参考我的分支 [mcxinyu/Android-So-Handler](https://github.com/mcxinyu/Android-So-Handler)

大佬，可以打包了，添加so文件压缩，发现打完包，包体大小无变化，你那边有效果吗？

**Comment by mcxinyu** [comment]
> > > 我也遇到同样的问题，请问楼主怎么解决呢？
> > 
> > 
> > 可以参考我的分支 [mcxinyu/Android-So-Handler](https://github.com/mcxinyu/Android-So-Handler)
> 
> 大佬，可以打包了，添加so文件压缩，发现打完包，包体大小无变化，你那边有效果吗？

你的步伐比我快😄。
这个应该根据原作分析，我这边应该影响有限。

**Comment by zwwxj** [comment]
> 项目里面 package 相关的 task 只有这几个

哈哈哈哈，看你下午一直在修复这个问题

**Comment by mcxinyu** [comment]
> 

嗯，一直在修复打包的问题，我这边还没到实际接入
